name: NUtilsX
version: '${project.version}'
main: com.nekozouneko.nutilsx.NUtilsXSpigot
api-version: 1.13
authors: [ Taitaitatata ]
description: NUtilsの書き直しバージョンです。仕組み全部を書き直し色々なユーティリティやデバッガーを提供します。

#commands:
#    test:
#        aliases: []
#        description: "Test"
#        permission: "nutilsx.command.test"
#        usage: "/<command>"
